namespace Modules.Game.Enums
{
    public enum EPantryType
    {
        None = 0,
        Almonds = 1,
        Baking_Powder = 2,
        Bean_Sprout = 3,
        Beans = 4,
        Beef_Stock = 5,
        Bread = 6,
        Butter = 7,
        Cheddar= 8,
        Cheese = 9,
        Chickpea = 10,
        Chocolatte = 11,
        Coconut_Milk = 12,
        Dough = 13,
        Dry_Oats = 14,
        Dry_Yeast = 15,
        Flour = 16,
        Heavy_Cream = 17,
        Mexican_Beans = 18,
        Milk = 19,
        Mozarella = 20,
        Noodle = 21,
        Nori = 22,
        Olives= 23,
        Olive_Oil = 24,
        Pasta = 25,
        Peanut = 26,
        Pickles = 27,
        Puff_Pastry = 28,
        Raisins = 29,
        Rice = 30,
        Sesame = 31,
        Sugar = 32,
        Tomato_Paste = 33,
        Tortilla = 34,
        Walnuts = 35,
        Wheat = 36,
        Vinegar = 37,
        Yogurt = 38,
    }
}